name: Demo de testes

on:
  pull_request:
    types: [closed]

jobs:
  check-build-sei-la:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged || github.event.pull_request.closed_at

    steps:
      - name: Check pull request status
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "MERGEADO!"
          elif [[ "${{ github.event.pull_request.state }}" == "closed" && "${{ github.event.pull_request.merged }}" == "false" ]]; then
            echo "FECHADO!"
          fi
