name: Build and Test

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Cache the npm or yarn packages to speed up builds
    # Note that we use the "hashFiles" option to only cache if the contents of the package.json and yarn.lock or
    # package-lock.json files have changed
    env:
      CACHE_NAME: cache-node-modules-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm ~/.cache/yarn
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}
            ${{ runner.os }}-
    
      # Install dependencies using either npm or yarn
      - name: Install Dependencies
        run: |
          if [[ -f yarn.lock ]]; then
            yarn install
          else
            npm ci
          fi
    
      # Build the project
      - name: Build Project
        run: |
          # Replace this with your own build command
          npm run build
    
      # Run tests
      - name: Run Tests
        run: |
          # Replace this with your own test command
          npm run test
